apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-checkclusteroperator
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    donotenforce: true
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-checkclusteroperator
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'False'
                      type: Available
                    - status: 'True'
                      type: Degraded
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-checkclusteroperator
placementRef:
  name: placement-checkclusteroperator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-checkclusteroperator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-checkclusteroperator
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster
      monitoring: true


